COLUMN STATUS        FORMAT A10
COLUMN TABLE_NAME    FORMAT A30
COLUMN FK_NAME       FORMAT A30
COLUMN FK_COLUMNS    FORMAT A60
COLUMN INDEX_NAME    FORMAT A30
COLUMN INDEX_COLUMNS FORMAT A30
COLUMN TABLE_OWNER   FORMAT A30

SELECT
   A.OWNER           AS TABLE_OWNER,
   A.TABLE_NAME      AS TABLE_NAME,
   A.CONSTRAINT_NAME AS FK_NAME,
   A.FK_COLUMNS      AS FK_COLUMNS,
   B.INDEX_NAME      AS INDEX_NAME,
   B.INDEX_COLUMNS   AS INDEX_COLUMNS
FROM
(  SELECT
      A.TABLE_NAME, A.CONSTRAINT_NAME, A.OWNER, LISTAGG(A.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY A.POSITION) FK_COLUMNS
   FROM
      DBA_CONS_COLUMNS A,DBA_CONSTRAINTS B 
   WHERE A.CONSTRAINT_NAME = B.CONSTRAINT_NAME
      AND B.CONSTRAINT_TYPE = 'R'
      AND A.OWNER LIKE ('%&&SCHEMA_OWNER%')
      AND A.OWNER NOT IN ('SYS', 'SYSTEM', 'MDSYS', 'GSMADMIN_INTERNAL', 'ORDDATA', 'LBACSYS')
      AND A.OWNER = B.OWNER
   GROUP BY
      A.TABLE_NAME, A.CONSTRAINT_NAME, A.OWNER ) A,
(  SELECT
      TABLE_NAME, INDEX_NAME, LISTAGG(C.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY C.COLUMN_POSITION) INDEX_COLUMNS
   FROM
      DBA_IND_COLUMNS C
   WHERE C.INDEX_OWNER LIKE ('%&&SCHEMA_OWNER%')
      AND C.INDEX_OWNER NOT IN ('SYS', 'SYSTEM', 'MDSYS', 'GSMADMIN_INTERNAL', 'ORDDATA', 'LBACSYS')
   GROUP BY
      TABLE_NAME, INDEX_NAME) B
WHERE A.TABLE_NAME = B.TABLE_NAME(+)
   AND B.TABLE_NAME IS NULL
   AND B.INDEX_COLUMNS(+) LIKE A.FK_COLUMNS || '%'
ORDER BY
   1, 2 ASC, 3;